version: '2'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  minio1:
    container_name: mongo_backup_minio
    image: minio/minio
    volumes:
      - //c/data:/data
    ports:
      - "9001:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: myminio
      MINIO_SECRET_KEY: myexample

networks:
  default:
    external:
      name: mongo